version: 2

sources:
  - name: nba
    database: raw
    schema: dbt_jvegter
    loader: Snowflake
    
    quoting:
      database: false
      schema: false
      identifier: false
      
    tables:
      - name: src_playedgames
      - name: src_playerstats
